---

- name: remove uneeded packages
  become: yes
  apt:
    name: 
      - apport
      - mailutils
      - at
      - avahi-utils 
      - cups
      - nfs-kernel-server
      - nfs-common
      - portmap
      - rpcbind
      - autofs
      - snmp
      - telnetd
      - inetutils-telnet
      - telnetd-ssl 
      - whoopsie
      - zeitgeist-core 
      - zeitgeist-datahub
      - python-zeitgeist
      - rhythmbox-plugin-zeitgeist
      - zeitgeist
      - rsh-redone-server
      - telnetd rsh-server
      - tftpd-hpa 
      - atftpd
      - tftpd
      - yp-tools
      - nis
      - xinetd 
    state: absent
    purge: yes 
    autoremove: yes
    autoclean: yes
