---
- name: Ensure wheel group is present
  become: yes
  group:
    name: wheel
    state: present
  
- name: Ensure wheel group has sudo privileges
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
  
- name: Install the `sudo` package
  become: yes
  package:
    name: sudo
    state: latest

- name: Include pass_vault variable
  include_vars: 
    file: pass_vault.yml

- name: Create the non-root user account
  become: yes
  user:
    name: "{{ user_name }}"
    password: "{{ my_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
    groups: wheel
    append: yes
   




  
