---

- name: Update apt-get repo and cache
  become: yes
  apt:
    update_cache: yes
 
- name: Update all packages to the latest version
  become: yes 
  apt:
    upgrade: dist 
 
- name: install additional packages
  become: true
  apt:
    name: 
      - vim
      - htop
      - ufw
      - mosh 
      - git
      - nano
      - wget
      - python3-pip
      - python3-venv
      - bleachbit
      - snapd
      - gcc
      - make
      - parallel
      - jq
      - gnupg2
      - software-properties-common
      - curl
      - build-essential
      - iproute2
      - net-tools
      - apt-transport-https
      - gnupg-agent
      - ca-certificates 
      - pwgen
      - secure-delete
    state: present
    update_cache: true
  

 









