---
- block: 

  - name: 'bleachbit : copy bleachbit_4.2.0-0_all_ubuntu10804.deb to /home/{{ user_name }}'
    become: yes
    become_user: "{{ user_name }}"
    copy:
      src: ../../../../../../Ansible-Config/bleachbit_4.2.0-0_all_ubuntu1804.deb 
      dest: /home/{{ user_name }}/

  - name: 'bleachbit : install bleachbit_4.2.0-0_all_ubuntu10804.deb'
    become: yes
    apt:
      deb: /home/{{ user_name }}/bleachbit_4.2.0-0_all_ubuntu1804.deb 

  - name: 'bleachbit : cleanup fragments'
    become: yes
    become_user: "{{ user_name }}"
    file:
      dest: /home/{{ user_name }}/bleachbit_4.2.0-0_all_ubuntu1804.deb 
      state: absent

  tags:
    - anonymity
    - bleachbit 
    