---
- block:

  - name: 'covermyass : download covermyass'
    git:
      repo: https://github.com/sundowndev/go-covermyass
      dest: /home/{{ user_name }}/go-covermyass

  - name: 'covermyass : install dependancies for covermyass'
    become: yes
    become_user: "{{ user_name }}"
    shell: /usr/local/go/bin/go get -v -t -d ./...
    args:
      chdir: /home/{{ user_name }}/go-covermyass

  - name: 'covermyass : build covermyass'
    shell: /usr/local/go/bin/go build -v .
    args:
      chdir: /home/{{ user_name }}/go-covermyass

  - name: 'covermyass : make go-covermyass executable'
    copy:
      src: /home/{{ user_name }}/go-covermyass/go-covermyass
      dest: /usr/local/bin/
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0755'
      remote_src: true

  tags:
    - anonymity
    - covermyass