---
- block:

  - name: 'vpn : Install wireguard'
    apt:
      update_cache: yes
      name: wireguard

  - name: 'vpn : copy dnsleaktest.sh into /usr/local/bin/'
    template:
      src: templates/dnsleaktest.j2
      dest: /usr/local/bin/dnsleaktest
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0755'

  - name: format RAW lynis output and remove /home/{{ user_name }}/lynis-master
    shell: "{{ item }}"
    args:
      chdir: /home/{{ user_name }}/{{ directory }}
      warn: no
    with_items:
      - dnsleaktest > RAW-dnsleaktest.txt
      - cat RAW-dnsleaktest.txt | ansi2txt > 'DNSLEAKTEST-{{ directory }}.txt'
      - srm -vz RAW-dnsleaktest.txt
   
  - name: 'vpn : Install speedtest-cli with pip3'
    become: yes
    become_user: "{{ user_name }}"
    pip:
      name: speedtest-cli
      executable: pip3

  - name: run speedtest-cli and write to file
    become: yes
    become_user: "{{ user_name }}"
    shell: speedtest-cli > 'SPEEDTEST-{{ DIRECTORY }}'
    args:
      chdir: /home/{{ user_name }}/{{ directory }}

  tags:
    - anonymity
    - vpn  