---
- name: Add local public key for key-based SSH authentication
  become: yes
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', public_key) }}"
  tags: ssh 

- name: Harden sshd configuration
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding no"
    - regexp: "^#?AllowTcpForwarding"
      line: "AllowTcpForwarding no"
    - regexp: "^#?MaxAuthTries"
      line: "MaxAuthTries 2"
    - regexp: "^#?MaxSessions"
      line: "MaxSessions 2"
    - regexp: "^#?TCPKeepAlive"
      line: "TCPKeepAlive no"
    - regexp: "^#?UseDNS"
      line: "UseDNS no"
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding no"
    - regexp: "^#?IgnoreRhosts "
      line: "IgnoreRhosts yes"
    - regexp: "^#?HostbasedAuthentication"
      line: "HostbasedAuthentication no"
    - regexp: "^#?LoginGraceTime"
      line: "LoginGraceTime 300"
    - regexp: "^#MaxStartups 10:30:100$"
      line: "MaxStartups 2"
    - regexp: "^#?AllowTcpForwarding"
      line: "AllowTcpForwarding no"
    - regexp: "^X11Forwarding?"
      line: "X11Forwarding no"
    - regexp: "^#?StrictModes"
      line: "StrictModes yes"
    - regexp: "^#?ClientAliveInterval"
      line: "ClientAliveInterval 300"
    - regexp: "^#?ClientAliveCountMax "
      line: "ClientAliveCountMax 0"
    - regexp: "^#?PrintLastLog"
      line: "PrintLastLog no"
    - regexp: "^#?PermitUserEnvironment"
      line: "PermitUserEnvironment no"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"

- name: add lines to ssh configuration
  become: yes
  blockinfile:
    dest: /etc/ssh/sshd_config
    state: present
    insertafter: '^IgnoreRhosts'
    block: |
      RhostsAuthentication no
      RhostsRSAAuthentication no
      RSAAuthentication yes
      Protocol 2
 
- name: Harden pamd./sshd   
  become: yes
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^session    optional     pam_motd.so  motd=/run/motd.dynamic?"
      line: "#session    optional     pam_motd.so  motd=/run/motd.dynamic"
    - regexp: "^session    optional     pam_motd.so noupdate?"
      line: "#session    optional     pam_motd.so noupdate"





