---

- name: Install auditd and audispd-plugins
  apt:
    name: 
      - auditd
      - audispd-plugins
    state: present

- name: copy audit.rules to /etc/audit/
  copy:
    src: templates/audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    force: yes 
    owner: root
    group: root
    mode: 0644
  
- name: "restart auditd"
  systemd:
    name: auditd
    state: restarted
 
- name: enable service auditd and ensure it is not masked
  systemd:
    name: auditd
    enabled: yes
    masked: no

- name: 'reboot machine for auditd to see if rules where applied'
  reboot:
    reboot_timeout: 300
      
- name: 'check uptime for auditd reboot'
  shell: uptime
  register: UPTIME_POST_REBOOT

- debug: msg={{UPTIME_POST_REBOOT.stdout}}

- name: list auditd rules and write to file and run aditd for for first time
  shell: "{{ item }}"
  args:
    chdir: /home/{{ user_name }}/{{ directory }}
  with_items:
    - auditctl -l > 'auditd-rules-{{ directory }}.txt' 
    - aureport > 'auditd-first-run-{{ directory }}.txt' 








 
 


