---

- name: Install the ufw package
  package:
    name: ufw
    state: latest
  
- name: Install the iptables-persistent package 
  package:
    name: iptables-persistent
    state: latest
  
- name: setup ufw rules script
  script: iptables.sh

- name: Enable netfilter-persistent.service for iptables
  systemd:
    name: netfilter-persistent.service
    state: started
    enabled: yes
  
- name: setup ufw rules script
  become: yes
  script: firewall.sh
  
- name: add lines to /etc/before.rules
  blockinfile:
    path: /etc/ufw/before.rules 
    state: present
    block: |
      ##Prevent Ping Flood##
      -A INPUT -p icmp -m limit --limit 6/s --limit-burst 1 -j ACCEPT
      -A INPUT -p icmp -j DROP

      # allow outbound icmp
      -A ufw-before-output -p icmp -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
      -A ufw-before-output -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
    insertbefore: "COMMIT"
  
- name: reload ufw with shell module
  shell: ufw reload

- name: get ufw status by numbers
  shell: ufw status numbered > 'UFW-status-{{ directory }}.txt'
  args:
    chdir: /home/{{ user_name }}/{{ directory }}
  register: ufw

- debug:
    msg: ufw.stdout

- name: backup iptable rules to {{ directory }}
  shell: "{{ item }}"
  args:
    chdir: /home/{{ user_name }}/{{ directory }}
  with_items:
    - iptables-save > rules.v4.txt
    - iptables-save > rules.v6.txt
    - systemctl status netfilter-persistent.service > iptables-status.txt
    




      




  