---
    
- name: allow root for cron, disable anacron and remove at 
  become: yes
  script: secure-cron.sh

- name: Set User/Group Owner and Permission on cron
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /home/{{ user_name }}
    warn: no
  with_items:
    -  chown root:root /etc/crontab
    -  chmod og-rwx /etc/crontab
    -  chown root:root /etc/cron.hourly
    -  chmod og-rwx /etc/cron.hourly
    -  chown root:root /etc/cron.daily
    -  chmod og-rwx /etc/cron.daily
    -  chown root:root /etc/cron.weekly
    -  chmod og-rwx /etc/cron.weekly
    -  chown root:root /etc/cron.monthly
    -  chmod og-rwx /etc/cron.monthly
    -  chown root:root /etc/cron.d
    -  chmod og-rwx /etc/cron.d
  
