---

- name: set limits on limit.conf 
  shell: sed -i '$d' /etc/security/limits.conf
  args:
    warn: no
  register: shell_output

- debug: var=shell_output

- name: set limits on limit.conf 
  shell: echo "root hard nproc 100" | sudo tee -a /etc/security/limits.conf
  args:
    warn: no
  register: shell_output
        
- debug: var=shell_output

- name: set limits on limit.conf 
  shell: echo "@root hard nproc 20" | sudo tee -a /etc/security/limits.conf
  args:
    warn: no
  register: shell_output
        
- debug: var=shell_output
  
- name: set limits on limit.conf 
  shell: echo "{{ user_name | quote }} hard nproc 100" | sudo tee -a /etc/security/limits.conf
  args:
    warn: no
  register: shell_output
        
- debug: var=shell_output
   
- name: set limits on limit.conf 
  shell: echo "@{{ user_name | quote }} hard nproc 20" | sudo tee -a /etc/security/limits.conf
  args:
    warn: no
  register: shell_output
        
- debug: var=shell_output
  


