---
- block:
  
  - name: 'docker : Add Docker apt key'
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    ignore_errors: true

  - name: 'docker : Add Docker repo'
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable" 
      update_cache: yes

  - name: Update apt-get repo and cache
    apt:
      update_cache: yes

  - name: 'docker : Install Docker apt package'
    apt:
      pkg: docker-ce
      state: latest
      update_cache: yes
   
  - name: 'docker : Ensure Docker service is installed and restarted'
    service:
      name: docker
      state: restarted
      enabled: yes

  - name: 'docker : add non root user to docker group.'
    user:
      name: "{{ user_name }}"
      groups: docker
      append: yes

  - name: 'docker : Install docker-compose'
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.28.0-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
      
  tags:
  - common
  - docker 
