---
sysctl_settings:
  name: kernal.printk 
  value: 4 4 1 7 
  name: kernal.panic 
  value: 10 
  name: kernal.sysrq 
  value: 0 
  name: kernal.shmmax 
  value: 4294967296 
  name: kernal.shmall 
  value: 4194304 
  name: kernal.core_uses_pid 
  value: 1 
  name: kernal.msgmnb 
  value: 65536 
  name: kernal.msgmax 
  value: 65536 
  name: vm.swappiness 
  value: 20 
  name: vm.dirty_ratio 
  value: 80 
  name: vm.dirty_background_ratio 
  value: 5 
  name: fs.file-max 
  value: 2097152 
  name: net.core.netdev_max_backlog 
  value: 262144 
  name: net.core.rmem_default 
  value: 31457280 
  name: net.core.rmem_max 
  value: 67108864 
  name: net.core.wmem_default 
  value: 31457280 
  name: net.core.wmem_max 
  value: 67108864 
  name: net.core.somaxconn 
  value: 65535 
  name: net.core.optmem_max 
  value: 25165824 
  name: net.ipv4.neigh.default.gc_thresh1 
  value: 4096 
  name: net.ipv4.neigh.default.gc_thresh2 
  value: 8192 
  name: net.ipv4.neigh.default.gc_thresh3 
  value: 16384 
  name: net.ipv4.neigh.default.gc_interval 
  value: 5 
  name: net.ipv4.neigh.default.gc_stale_time 
  value: 120 
  name: net.netfilter.nf_conntrack_max 
  value: 10000000 
  name: net.netfilter.nf_conntrack_tcp_loose 
  value: 0 
  name: net.netfilter.nf_conntrack_tcp_timeout_established 
  value: 1800 
  name: net.netfilter.nf_conntrack_tcp_timeout_close 
  value: 10 
  name: net.netfilter.nf_conntrack_tcp_timeout_close_wait 
  value: 10 
  name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait 
  value: 20 
  name: net.netfilter.nf_conntrack_tcp_timeout_last_ack 
  value: 20 
  name: net.netfilter.nf_conntrack_tcp_timeout_syn_recv 
  value: 20 
  name: net.netfilter.nf_conntrack_tcp_timeout_syn_sent 
  value: 20 
  name: net.netfilter.nf_conntrack_tcp_timeout_time_wait 
  value: 10 
  name: net.ipv4.tcp_slow_start_after_idle 
  value: 0 
  name: net.ipv4.ip_local_port_range 
  value: 1024 65000 
  name: net.ipv4.ip_no_pmtu_disc 
  value: 1 
  name: net.ipv4.route.flush 
  value: 1 
  name: net.ipv4.route.max_size 
  value: 8048576 
  name: net.ipv4.icmp_echo_ignore_broadcasts 
  value: 1 
  name: net.ipv4.icmp_ignore_bogus_error_responses 
  value: 1 
  name: net.ipv4.tcp_congestion_control 
  value: htcp 
  name: net.ipv4.tcp_mem 
  value: 65536 131072 262144 
  name: net.ipv4.udp_mem 
  value: 65536 131072 262144 
  name: net.ipv4.tcp_rmem 
  value: 4096 87380 33554432 
  name: net.ipv4.udp_rmem_min 
  value: 16384 
  name: net.ipv4.tcp_wmem 
  value: 4096 87380 33554432 
  name: net.ipv4.udp_wmem_min 
  value: 16384 
  name: net.ipv4.tcp_max_tw_buckets 
  value: 1440000 
  name: net.ipv4.tcp_tw_recycle 
  value: 0 
  name: net.ipv4.tcp_tw_reuse 
  value: 1 
  name: net.ipv4.tcp_max_orphans 
  value: 400000 
  name: net.ipv4.tcp_window_scaling 
  value: 1 
  name: net.ipv4.tcp_rfc1337 
  value: 1 
  name: net.ipv4.tcp_syncookies 
  value: 1 
  name: net.ipv4.tcp_synack_retries 
  value: 1 
  name: net.ipv4.tcp_syn_retries 
  value: 2 
  name: net.ipv4.tcp_max_syn_backlog 
  value: 16384 
  name: net.ipv4.tcp_timestamps 
  value: 1 
  name: net.ipv4.tcp_sack 
  value: 1 
  name: net.ipv4.tcp_fack 
  value: 1 
  name: net.ipv4.tcp_ecn 
  value: 2 
  name: net.ipv4.tcp_fin_timeout 
  value: 10 
  name: net.ipv4.tcp_keepalive_time 
  value: 600 
  name: net.ipv4.tcp_keepalive_intvl 
  value: 60 
  name: net.ipv4.tcp_keepalive_probes 
  value: 10 
  name: net.ipv4.tcp_no_metrics_save 
  value: 1 
  name: net.ipv4.ip_forward 
  value: 0 
  name: net.ipv4.conf.all.accept_redirects 
  value: 0 
  name: net.ipv4.conf.all.send_redirects 
  value: 0 
  name: net.ipv4.conf.all.accept_source_route 
  value: 0 
  name: net.ipv4.conf.all.rp_filter 
  value: 1